Don't do shallow clones if upstream does not support this
Since we changes our cloning strategy to do shallow clones only,
all CI builds broke because the upstream servers don't allow us
to clone specific commits. The error reads like this:

  error: Server does not allow request for unadvertised object
  beb2cdbcda911764b2bed5e57921fe90493260bd
  fatal: Fetched in submodule path 'binutils', but it did not
  contain beb2cdbcda911764b2bed5e57921fe90493260bd. Direct fetching
  of that commit failed.

What we could do is to search for our target commit in remote branches,
fetch those and then checkout our target commit. See also the following
comment for an idea how this could be realized:
  https://github.com/riscv-collab/riscv-gnu-toolchain/
  issues/1654#issuecomment-2591195261

However, it feels wrong to do add such scripts downstream.
We need to find a better solution. But unless we have one,
let's just disable shallow clones to unbreak the CI builds.

Signed-off-by: Christoph Müllner <christoph.muellner@vrull.eu>